name: Glower
version: 1.1
description: Plugin that enables players to glow a color of their choice
author: Alfie Smith
main: net.alfiesmith.glower.Glower
commands:
  glower:
    description: Opens glow GUI
    usage: /glower